name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Make all
      run: make
   
    - name: Create submission output
      run: java -jar cgproject.jar -gui false

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: ./*.png
        commit_message: CI rendered image
